<?php

namespace Otus\Models\Lists;

use Bitrix\Main\Entity\ReferenceField;
use Otus\Models\AbstractIblockPropertyValuesTable;

class DoctorsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 17;

    // public static function getMap(): array
    // {
    //     $map = [
    //         'PROC' => new ReferenceField(
    //             'PROC', 
    //             DoctorsProcPropertyValuesTable::class, 
    //             ['=this.PROC_ID' => 'ref.IBLOCK_ELEMENT_ID']
    //         )
    //     ];

    //     return parent::getMap() + $map; // TODO: Change the autogenerated stub

    // }
}
